### ISSUE TITLE
Tab shadow and highlighting from Firefox Proton

### ISSUE THREAD

**Issue by bigteefcat** [migueravila/SimpleFox#31]
Firefox proton causes tab highlighting when you hover over tabs as well as a shadow on the tab that is active. 
Could you make these the same color as the set primary color because it ruins the look right now. 

Proton became default on nightly a day or two ago and I can still disable it but itll become a problem when firefox fully moves to proton and the option to disable it gets removed.

**Comment by migueravila** [comment]
@bigteefcat I've just updated the theme. Checkout if it works now!
