### ISSUE TITLE
New Firefox Proton UI messes with the add-on right click bar

### ISSUE THREAD

**Issue by MiliAxe** [migueravila/SimpleFox#34]
My firefox dev edition has recently been updated to the newest version in which they have introduced the proton UI, However the `Almost McManjaro` add-on seems to have some issues with the right click bar: 
![Screenshot 2021-04-21 094321](https://user-images.githubusercontent.com/55515322/115500172-0baaea80-a286-11eb-92c5-2ef3a63b32e8.png)

**Comment by MiliAxe** [comment]
Looks like the selection menu is also affected: 
![Screenshot 2021-04-21 094321](https://user-images.githubusercontent.com/55515322/115553952-39625480-a2c3-11eb-907f-f8f7804ea55b.png)

**Comment by MiliAxe** [comment]
Looks like the selection menu is also affected: 
![Screenshot 2021-04-21 170219](https://user-images.githubusercontent.com/55515322/115554130-63b41200-a2c3-11eb-85d1-ee72a1bfb588.png)

**Comment by MiliAxe** [comment]
The problem was fixed by replacing the userChrome.css and userContent.css with the newer versions. however it would be great if it was possible to have the dark right click menu back: 
![Screenshot 2021-04-22 103319](https://user-images.githubusercontent.com/55515322/115663737-2d73a280-a356-11eb-8ce0-a8cdd4ff48ef.png)

**Comment by jruaaa** [comment]
Check out my commit, i also use the https://addons.mozilla.org/en-US/firefox/addon/matte-black-red/ theme personally so I can't help you with that one

**Comment by MiliAxe** [comment]
Does your tabs don't have the proper height as well? for example, the bottom red border here is not shown:

![image](https://user-images.githubusercontent.com/55515322/121735060-dc3c8f80-cb0a-11eb-825b-fcaea9dad598.png)
