### ISSUE TITLE
Default GTK color, I want to use the system default color on tabs. (ZorinOS / Linux)

### ISSUE THREAD

**Issue by Blackrucat** [migueravila/SimpleFox#40]
![image](https://user-images.githubusercontent.com/56588184/133805216-4c5228d7-7ed9-4ba6-8ec9-58a6e07e786e.png)
It looks like that, I want it to be the same as the menu on the top, like the rest of the system.

**Comment by migueravila** [comment]
Hey @Blackrucat You have to modify the css file of the theme you're using.
